src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $pseudo = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $birthday = null;

    #[ORM\Column]
    private ?int $age = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $avatar = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $modified_at = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Comment::class)]
    private Collection $comments;

    #[ORM\ManyToOne(inversedBy: 'user')]
    private ?Address $address = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Order::class)]
    private Collection $orders;

    #[ORM\Column]
    private ?bool $isVerified = null;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->orders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): static
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(\DateTimeInterface $birthday): static
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(int $age): static
    {
        $this->age = $age;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): static
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getModifiedAt(): ?\DateTimeImmutable
    {
        return $this->modified_at;
    }

    public function setModifiedAt(\DateTimeImmutable $modified_at): static
    {
        $this->modified_at = $modified_at;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    public function getAddress(): ?Address
    {
        return $this->address;
    }

    public function setAddress(?Address $address): static
    {
        $this->address = $address;

        return $this;
    }

    /**
     * @return Collection<int, Order>
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): static
    {
        if (!$this->orders->contains($order)) {
            $this->orders->add($order);
            $order->setUser($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): static
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getUser() === $this) {
                $order->setUser(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->getFirstname().' '.$this->getLastname();
    }

    public function isIsVerified(): ?bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }
}

src/Frontend/Entity/Tag.php
<?php

namespace App\Frontend\Entity;

use App\Frontend\Repository\TagRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TagRepository::class)]
class Tag
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\ManyToMany(targetEntity: Article::class, inversedBy: 'tags')]
    private Collection $articles;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): static
    {
        if (!$this->articles->contains($article)) {
            $this->articles->add($article);
        }

        return $this;
    }

    public function removeArticle(Article $article): static
    {
        $this->articles->removeElement($article);

        return $this;
    }
}

src/Frontend/Controller/BasketController.php
<?php

namespace App\Frontend\Controller;

use App\Entity\Order;
use App\Entity\RowOrder;
use App\Repository\OrderRepository;
use App\Repository\ProductRepository;
use App\Repository\RowOrderRepository;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/panier',name:'panier_')]
class BasketController extends AbstractController
{
    private $productRepository;
    private $orderRepository;
    private $rowOrderRepository;

    public function __construct( ProductRepository $productRepository, OrderRepository $orderRepository,RowOrderRepository $rowOrderRepository){
        $this->productRepository = $productRepository;
        $this->orderRepository = $orderRepository;
        $this->rowOrderRepository = $rowOrderRepository;
    }

    #[Route('/home', name: 'home')]
    public function panier(SessionInterface $session): Response
    {
        $panier = $session->get('panier', []);
        $panierWithData = [];
        foreach ($panier as $id => $quantity) {
            $panierWithData[] = [
                'product' => $this->productRepository->find($id),
                'quantity' => $quantity
            ];
        }
        $total = 0;
        foreach ($panierWithData as $item) {
            $totalItem = $item['product']->getPrice() * $item['quantity'];
            $total += $totalItem;
        }
        return $this->render('frontend/paiement/panier.html.twig',[
            'items' => $panierWithData,
            'total' => $total,
        ]);
    }

    #[Route('/resume-basket/{quantityTotal}/{step}', name: 'resum')]
    public function panierResume(SessionInterface $session, EntityManagerInterface $em, $quantityTotal = null, $step = null): Response
    {
        if ($step != 'commande') {
            return $this->redirectToRoute('panier_home');
        }

        $user = $this->getUser();
        $orderExist = $this->orderRepository->findOneBy(['user' => $user, 'step' => 0]);
        $panierWithData = [];
        if (!$orderExist) {
            $order = new Order;
            $order->setStep(0)
            ->setCreatedAt(new DateTimeImmutable())
            ->setUser($user);
    
            $panier = $session->get('panier', []);
            foreach ($panier as $id => $quantity) {
                $product = $this->productRepository->find($id);
                $panierWithData[] = [
                    'product' => $product,
                    'quantity' => $quantity
                ];
    
                $row = new RowOrder();
                $row->setNameProduct($product->getName())
                ->setDescriptionProduct($product->getDescription())
                ->setQuantity($quantity)
                ->setUnitPrice($product->getPrice())
                ->setProduct($product)
                ->setBasketOrder($order);
    
                $em->persist($row);
            }
            $em->persist($order);
            $em->flush();
        }else{
            $rowOrder = $this->rowOrderRepository->findBy(['basketOrder' => $orderExist]);
            for ($i=0; $i < count($rowOrder); $i++) { 
                $orderExist->removeRowOrder($rowOrder[$i]);
                $em->remove($rowOrder[$i]);
                $em->flush();
            }
            
            $panier = $session->get('panier', []);
            foreach ($panier as $id => $quantity) {
                $product = $this->productRepository->find($id);
                $panierWithData[] = [
                    'product' => $product,
                    'quantity' => $quantity
                ];
    
                $row = new RowOrder();
                $row->setNameProduct($product->getName())
                ->setDescriptionProduct($product->getDescription())
                ->setQuantity($quantity)
                ->setUnitPrice($product->getPrice())
                ->setProduct($product)
                ->setBasketOrder($orderExist);
    
                $em->persist($row);
                $em->flush();
            }
        }
        $total = 0;
        foreach ($panierWithData as $item) {
            $totalItem = $item['product']->getPrice() * $item['quantity'];
            $total += $totalItem;
        }
        return $this->render('frontend/paiement/resum_basket.html.twig',[
            'items' => $panierWithData,
            'total' => $total,
            'quantityTotal' => $quantityTotal
        ]);
    }



    #[Route('/add', name: 'add')]
    public function panierAdd(SessionInterface $session, Request $request, ProductRepository $productRepository)
    {
        $data = json_decode($request->getContent(), true);
        $id = $data['productId'];
        $quantity = $data['quantity'];
        $panier = $session->get('panier', []);
        if (!empty($panier[$id])) {
            $panier[$id] = $panier[$id] + $quantity;
        }else{
            $panier[$id] = $quantity;
        }
        $panierWithData = [];
        foreach ($panier as $id => $quantity) {
            $panierWithData[] = [
                'product' => $productRepository->find($id),
                'quantity' => $quantity
            ];
        }
        $totalAmount = 0;
        $numberOfItems = 0;
        foreach ($panierWithData as $item) {
            $totalItem = $item['product']->getPrice() * $item['quantity'];
            $totalAmount += $totalItem;
            $numberOfItems = $numberOfItems + $item['quantity'];
        }
        $totalAmount = $totalAmount / 100;
        $session->set('panier', $panier);
       $this->addFlash('success', 'Le produit à bien était ajouté au panier');
       return $this->json([
        'numberOfItems' => $numberOfItems,
        'totalAmount' => $totalAmount,
    ]);
    }

    #[Route('/remove/{id}', name: 'remove')]
    public function panierRemove(SessionInterface $session, $id): Response
    {
        $panier = $session->get('panier', []);
        if (!empty($panier[$id])) {
            unset($panier[$id]);
        }
        $session->set('panier', $panier);
        $this->addFlash('success', 'Le produit a bien était supprimer de votre panier');
        return $this->redirectToRoute('panier_home');
    }


}

src/Frontend/Controller/HomeController.php
<?php

namespace App\Frontend\Controller;

use App\Entity\ContentPage;
use App\Repository\ContentPageRepository;
use App\Repository\TagRepository;
use App\Repository\ProductRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Session\SessionInterface;

class HomeController extends AbstractController
{
    private $tagRepository;
    private $productRepository;

    public function __construct(TagRepository $tagRepository, ProductRepository $productRepository){
        $this->tagRepository = $tagRepository;
        $this->productRepository = $productRepository;
    }
    
    public function getNumberArticleInBasket(SessionInterface $session)
    {
        $panier = $session->get('panier', []);
        $panierWithData = [];
        foreach ($panier as $id => $quantity) {
            $panierWithData[] = [
                'product' => $this->productRepository->find($id),
                'quantity' => $quantity
            ];
        }
        $numberOfItems = 0;
        foreach ($panierWithData as $item) {
            $numberOfItems = $numberOfItems + $item['quantity'];
        }
        return $numberOfItems;
    }
    
    #[Route('/', name: 'home')]
    public function home(): Response
    {
        $tags = $this->tagRepository->findBy([],[],8);
        $lastsProducts = $this->productRepository->findBy([], ["published_at" => "DESC"], 15);
        $discountsProducts = $this->productRepository->getRandomProduct(4);
        return $this->render('frontend/pages/home.html.twig', [
            'tags' => $tags,
            'lastsProducts' => $lastsProducts,
            'discountsProducts' => $discountsProducts,
        ]);
    }

    #[Route('/mentions-legales', name: 'mention_legales')]
    public function mentionsLegale(): Response
    {
        return $this->render('frontend/pages/default/mentions_legales.html.twig');
    }

    #[Route('/politique-de-confidentialite', name: 'politique_de_confidentialite')]
    public function politiqueDeConfidentialite(): Response
    {
        return $this->render('frontend/pages/default/politique_de_confidentialite.html.twig');
    }

    #[Route('/equipe-de-dev', name: 'equipe_dev')]
    public function equipeDev(): Response
    {
        return $this->render('frontend/pages/default/equipe_de_dev.html.twig');
    }
}

templates/frontend/pages/product.html.twig
{% extends "frontend/template.html.twig" %}
{% block title %}{{product.name}}{% endblock %}
{% block body %}
<div class="row bg-hero-section">
    <div class="col-10 mx-auto d-flex justify-content-start align-items-end">
        <div class="block-title">
            <h1 class="title-hero-section">{{product.name}}</h1>
        </div>
    </div>
</div>
<div class="row my-5">
    <div class="col-10 mx-auto">
        <div class="row">
            <div class="col-12 col-xl-6">
                {% if product.pictures|length > 0 %}
                    <img id="picture-product-main" src="{{asset('img/products/' ~ product.pictures|first.file)}}" alt="" class="img-presentation-product">
                {% else %}
                    <img src="{{asset('img/final-fantasy.jpg')}}" alt="" class="img-presentation-product">
                {% endif %}
            </div>
            <div class="col-12 col-xl-6 d-flex align-items-center">
                <div>
                    {% for message in app.flashes('success') %}
                        <div class="alert alert-success">
                            {{ message }}
                        </div>
                    {% endfor %}
                    <div class="d-flex justify-content-between">
                    <h2>{{product.name}}</h2>
                    {% if comments|length > 0 %}
                        <p class="f-15r" style="font-weight:bold;">Note générale {{getNoteGeneral(product.id)}}/5</p>
                    {% endif %}
                    </div>
                    <p>{{product.description|raw}}</p>
                    <p class="f-2r">Prix : {{product.price / 100 }}€</p>
                    <div>
                        <div action="{{path('panier_add',{'id':product.id})}}" method="post" class="row">
                            <div class="col-5">
                                <button id="addToCartButton" class="btn btn-primary"><i class="feather-plus"></i> Ajouter au panier</button>
                            </div>
                        </div>
                        {% if product.pictures|length > 1 %}
                            <div class="row my-5">
                                <div class="col-10 mx-auto">
                                    <div class="d-flex flex-nowrap w-100">
                                        {% for picture in product.pictures %}
                                            <img src="{{asset('img/products/' ~ picture.file)}}" onclick="changePicture('{{asset('img/products/' ~ picture.file)}}')" class="pictures-products-other mx-3">
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                        <script>
                            document.getElementById('addToCartButton').addEventListener('click', function(){
                                let productId = {{product.id}}
                                let quantity = 1
                                fetch('{{path('panier_add')}}', {
                                    method: 'POST',
                                    headers: {
                                        'Content-Type': 'application/json',
                                    },
                                    body: JSON.stringify({ productId, quantity }),
                                })
                                .then(response => response.json())
                                .then(data => {
                                    // Mettez à jour l'affichage du nombre d'articles dans le panier et du total d'achat en utilisant les données reçues.
                                    var numberOfItems = data.numberOfItems; // Remplacez ceci par la clé correcte dans votre réponse JSON.
                                    var totalAmount = data.totalAmount; // Remplacez ceci par la clé correcte dans votre réponse JSON.
                                    let span = document.getElementById('numberOfItemsTotal')
                                    span.innerHTML = numberOfItems
                                    let span2 = document.getElementById('totalAmountTotal')
                                    span2.innerHTML = totalAmount
                                    // Mettez à jour votre interface utilisateur avec numberOfItems et totalAmount.
                                })
                                .catch(error => {
                                    console.error('Une erreur s\'est produite :', error);
                                });
                            });
                        </script>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row my-5">
    <div class="col-10 mx-auto">
        <h2 class="mb-5">Dans le même genre</h2>
        <div class="row">
            {% for i in 1..4 %}
                <div class="col-3">
                    <a href="#"  class="link-last-article">
                        <img src="{{asset('img/product.jpg')}}" alt="" class="promo-product">
                        <div class="row my-5">
                            <div class="col-6">
                                <p>Final Fantasy {{i}}</p>
                                <p>Prix <span class="price-barrer mx-1">50€</span> 20€</p>
                            </div>
                            <div class="col-6 d-flex align-items-center">
                                <button class="btn btn-primary">Voir le produit</button>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

{% include "frontend/_parts/lastArticle.html.twig" with {'title' : 'Dernier article rentrer' } %}

<div class="row my-5">
    <div class="col-10 mx-auto">
        <h2 class="mb-4">Commentaire sur ce produit</h2>
        {% if comments|length > 0 %}
            <div class="accordion" id="accordionExample">
                {% set idUserComment = [] %}
                {% for comment in comments %}
                    <div class="accordion-item">
                        <h2 class="accordion-header">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            Commentaire de {{comment.user.pseudo}}
                        </button>
                        </h2>
                        <div id="collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                            <div class="accordion-body">
                                <div class="d-flex justify-content-between">
                                    <p>Le {{comment.createdAt|date("m/d/Y")}}</p>
                                </div>
                                <p>Note {{comment.note}}/5</p>
                                <p>
                                    {{comment.text}}
                                </p>
                            </div>
                        </div>
                    </div>
                    {% set idUserComment = idUserComment|merge([comment.user.id]) %}
                {% endfor %}
                {% if app.user %}
                    {% if app.user.id in idUserComment %}
                    {% else %}
                        <button class="btn btn-primary my-3" data-bs-toggle="modal" data-bs-target="#exampleModal"><i class="feather-plus"></i> Ajouter un commentaire</button>
                    {% endif %}
                {% endif %}
            </div>
        {% else %}
            <p>Pas encore de commentaire pour ce produit</p>
            {% if app.user %}
                <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal"><i class="feather-plus"></i> Ajouter un commentaire</button>
            {% else %}
                <p>Il faut être connecté pour mettre un commentaire</p>
            {% endif %}
        {% endif %}
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form action="{{path('add_comment_product',{'idProduct':product.id})}}" method="post">
                            <div class="row mb-4">
                                <div class="col-12">
                                    <label for="noteProduct">Note(max : 5) :</label>
                                    <input type="number" class="form-control" min="0" max="5" name="noteProduct" id="noteProduct">
                                </div>
                            </div>
                            <div class="row mb-4">
                                <div class="col-12">
                                    <label for="messageComment">Message :</label>
                                    <textarea class="form-control" name="messageComment" id="messageComment" cols="30" rows="10"></textarea>
                                </div>
                            </div>
                            <div class="d-flex justify-content-end">
                                <button type="button" class="btn btn-secondary mx-3" data-bs-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary"><i class="feather-chevrons-right"></i> Commenter</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block addJS %}
<script>
function changePicture(image){
    let pictureMain = document.getElementById('picture-product-main')
    pictureMain.src = image
}

</script>
<script>
  document.addEventListener( 'DOMContentLoaded', function() {
    var splide = new Splide( '.splide' , {
        perPage: 4,
        type: 'loop',
        pagination: false,
        arrows: true,
        pauseOnFocus: true,
        autoplay: false,
        speed: 1000,
        });
    splide.mount();
  } );
</script>
{% endblock %}

templates/frontend/pages/profil.html.twig
{% extends "frontend/template.html.twig" %}
{% block title %}Votre Profil{% endblock %}
{% block body %}

<div class="row bg-hero-section">
    <div class="col-10 mx-auto d-flex justify-content-start align-items-end">
        <div class="block-title">
            <h1 class="title-hero-section font-f-special">Votre Profil</h1>
        </div>
    </div>
</div>

<div class="row my-5">
    <div class="col-10 mx-auto p-5 d-flex align-items-center justify-content-center" style="background-image:url('{{asset('img/bg-profil.webp')}}');background-size: cover;height: 41rem;">
        <div class="p-5 w-100" style="background-color: #ffffff6e;">
            {% for message in app.flashes('error') %}
                <div class="alert alert-danger">
                    {{ message }}
                </div>
            {% endfor %}
                {% for message in app.flashes('success') %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {% endfor %}
            <div class="row ">
                <div class="col-12" id="fieldPseudo">
                    <p style="font-weight:bold;font-size:1.2rem">Pseudo : {{user.pseudo}} <button hx-post="{{path('profil_edit',{'idUser':user.id,'field':'pseudo','type':'text'})}}" hx-trigger="click" hx-target="#fieldPseudo" class="btn btn-small btn-primary mx-3"><i class="feather-edit"></i></button></p>
                </div>
            </div>
            <div class="row">
                <div class="col-6" id="fieldFirstName">
                    <p style="font-weight:bold;font-size:1.2rem">Prénom : {{user.firstName}} <button hx-post="{{path('profil_edit',{'idUser':user.id,'field':'firstName','type':'text'})}}" hx-trigger="click" hx-target="#fieldFirstName" class="btn btn-small btn-primary mx-3"><i class="feather-edit"></i></button></p>
                </div>
                <div class="col-6" id="fieldLastName">
                    <p style="font-weight:bold;font-size:1.2rem">Nom : {{user.lastName}} <button hx-post="{{path('profil_edit',{'idUser':user.id,'field':'lastName','type':'text'})}}" hx-trigger="click" hx-target="#fieldLastName" class="btn btn-small btn-primary mx-3"><i class="feather-edit"></i></button></p>
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    <p style="font-weight:bold;font-size:1.2rem">Anniverssaire le : {{user.birthday|date("m/d/Y")}}</p>
                </div>
                <div class="col-6">
                    <p style="font-weight:bold;font-size:1.2rem">Age : {{user.age}}</p>
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    <p style="font-weight:bold;font-size:1.2rem">Créé le : {{user.createdAt|date("m/d/Y")}}</p>
                </div>
                <div class="col-6">
                    <p style="font-weight:bold;font-size:1.2rem">Modifié le : {{user.modifiedAt|date("m/d/Y")}}</p>
                </div>
            </div>
            <div class="row">
                <div class="col-12" id="fieldEmail">
                    <p style="font-weight:bold;font-size:1.2rem">Email : {{user.email}} <button hx-post="{{path('profil_edit',{'idUser':user.id,'field':'email','type':'email'})}}" hx-trigger="click" hx-target="#fieldEmail" class="btn btn-small btn-primary mx-3"><i class="feather-edit"></i></button></p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}